name: IOT IJK ANDROID DEBUG CI

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build with Gradle
        run: |
          sb .github/script/build_armv7a.sh
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:build
          ./gradlew :ijkplayer-java:build
